#!/bin/bash

# ============================================
# Railway 备选部署脚本
# 当 Cloudflare Containers 不可用时使用
# ============================================

set -e

echo "🚂 Railway 部署指南"
echo ""
echo "如果您无法使用 Cloudflare Containers，可以将 ElizaOS 服务部署到 Railway。"
echo ""
echo "============================================"
echo "手动部署步骤:"
echo "============================================"
echo ""
echo "1. 登录 Railway"
echo "   https://railway.app/"
echo ""
echo "2. 创建新项目"
echo "   - 点击 'New Project'"
echo "   - 选择 'Deploy from GitHub repo' 或 'Empty Project'"
echo ""
echo "3. 部署 ElizaOS Container"
echo "   - 如果从 GitHub: 选择此仓库，设置 Root Directory 为 'elizaos-container'"
echo "   - 如果空项目: 使用 railway CLI 部署"
echo ""
echo "4. 配置环境变量"
echo "   在 Railway 控制台中添加以下变量:"
echo ""
echo "   NODE_ENV=production"
echo "   PORT=3001"
echo ""
echo "   # Twitter (可选)"
echo "   TWITTER_API_KEY=xxx"
echo "   TWITTER_API_SECRET=xxx"
echo "   TWITTER_ACCESS_TOKEN=xxx"
echo "   TWITTER_ACCESS_TOKEN_SECRET=xxx"
echo ""
echo "   # Discord (可选)"
echo "   DISCORD_BOT_TOKEN=xxx"
echo ""
echo "   # Telegram (可选)"
echo "   TELEGRAM_BOT_TOKEN=xxx"
echo ""
echo "   # Solana (可选)"
echo "   SOLANA_PRIVATE_KEY=xxx"
echo "   SOLANA_RPC_URL=https://api.mainnet-beta.solana.com"
echo ""
echo "5. 获取部署 URL"
echo "   部署完成后，Railway 会提供一个 URL，例如:"
echo "   https://elizaos-server-production.up.railway.app"
echo ""
echo "6. 更新 Cloudflare 环境变量"
echo "   npx wrangler secret put ELIZAOS_CONTAINER_URL"
echo "   (输入 Railway 提供的 URL)"
echo ""
echo "============================================"
echo "Railway CLI 快速部署:"
echo "============================================"
echo ""
echo "# 安装 Railway CLI"
echo "npm install -g @railway/cli"
echo ""
echo "# 登录"
echo "railway login"
echo ""
echo "# 进入容器目录"
echo "cd elizaos-container"
echo ""
echo "# 初始化并部署"
echo "railway init"
echo "railway up"
echo ""
echo "============================================"
echo ""
echo "📚 更多信息: https://docs.railway.app/"
